DROP POLICY IF EXISTS "Admins can manage admins" ON "public"."system_admins";
DROP POLICY IF EXISTS "Admins can view admins" ON "public"."system_admins";
DROP POLICY IF EXISTS "Allow authenticated read access" ON "public"."realtime_events";
DROP POLICY IF EXISTS "Allow authenticated users to create attachments" ON "public"."forum_attachments";
DROP POLICY IF EXISTS "Allow owners to delete their attachments" ON "public"."forum_attachments";
DROP POLICY IF EXISTS "Allow public read access" ON "public"."forum_attachments";
DROP POLICY IF EXISTS "Allow authenticated users to create comments" ON "public"."forum_comments";
DROP POLICY IF EXISTS "Allow owners to delete their comments" ON "public"."forum_comments";
DROP POLICY IF EXISTS "Allow owners to update their comments" ON "public"."forum_comments";
DROP POLICY IF EXISTS "Allow public read access" ON "public"."forum_comments";
DROP POLICY IF EXISTS "Allow authenticated users to create topics" ON "public"."forum_topics";
DROP POLICY IF EXISTS "Allow owners to delete their topics" ON "public"."forum_topics";
DROP POLICY IF EXISTS "Allow owners to update their topics" ON "public"."forum_topics";
DROP POLICY IF EXISTS "Allow public read access" ON "public"."forum_topics";
DROP POLICY IF EXISTS "Allow authenticated users to insert" ON "public"."template_comments";
DROP POLICY IF EXISTS "Allow public read access" ON "public"."template_comments";
DROP POLICY IF EXISTS "Allow users to delete their own comments" ON "public"."template_comments";
DROP POLICY IF EXISTS "Allow users to update their own comments" ON "public"."template_comments";
DROP POLICY IF EXISTS "Allow authenticated users to insert their own movements" ON "public"."inventory_movements";
DROP POLICY IF EXISTS "Allow user access to their own inventory movements" ON "public"."inventory_movements";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."inventory_movements";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."inventory_movements";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."inventory_movements";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."inventory_movements";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."inventory_movements";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."inventory_movements";
DROP POLICY IF EXISTS "Allow authenticated users to manage their loyalty movements" ON "public"."loyalty_movements";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."loyalty_movements";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."loyalty_movements";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."loyalty_movements";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."loyalty_movements";
DROP POLICY IF EXISTS "Allow authenticated users to manage their own loyalty settings" ON "public"."loyalty_settings";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."loyalty_settings";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."loyalty_settings";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."loyalty_settings";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."loyalty_settings";
DROP POLICY IF EXISTS "Permitir leitura pública de configurações de fidelidade" ON "public"."loyalty_settings";
DROP POLICY IF EXISTS "Allow authenticated users to manage their own rewards" ON "public"."loyalty_rewards";
DROP POLICY IF EXISTS "Allow public read access for rewards" ON "public"."loyalty_rewards";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."loyalty_rewards";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."loyalty_rewards";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."loyalty_rewards";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."loyalty_rewards";
DROP POLICY IF EXISTS "Permitir leitura pública de prêmios de fidelidade" ON "public"."loyalty_rewards";
DROP POLICY IF EXISTS "Allow authenticated users to manage their own schedules" ON "public"."schedules";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."schedules";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."schedules";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."schedules";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."schedules";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."schedules";
DROP POLICY IF EXISTS "Allow authenticated users to manage their own shifts" ON "public"."shifts";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."shifts";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."shifts";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."shifts";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."shifts";
DROP POLICY IF EXISTS "Allow authenticated users to manage their own sync data" ON "public"."ifood_menu_sync";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."ifood_menu_sync";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."ifood_menu_sync";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."ifood_menu_sync";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."ifood_menu_sync";
DROP POLICY IF EXISTS "Allow authenticated users to read plan permissions" ON "public"."plan_permissions";
DROP POLICY IF EXISTS "Permitir leitura pública das permissões dos planos" ON "public"."plan_permissions";
DROP POLICY IF EXISTS "Allow authenticated users to read plans" ON "public"."plans";
DROP POLICY IF EXISTS "Permitir leitura pública dos planos" ON "public"."plans";
DROP POLICY IF EXISTS "Allow individual access" ON "public"."user_learning_progress";
DROP POLICY IF EXISTS "Allow public form submissions" ON "public"."contacts";
DROP POLICY IF EXISTS "Allow user access to their own cashier closings" ON "public"."cashier_closings";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."cashier_closings";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."cashier_closings";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."cashier_closings";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."cashier_closings";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."cashier_closings";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."cashier_closings";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."cashier_closings";
DROP POLICY IF EXISTS "Allow user access to their own employees" ON "public"."employees";
DROP POLICY IF EXISTS "Authenticated users can view employees" ON "public"."employees";
DROP POLICY IF EXISTS "Authenticated users can view employees in their organization" ON "public"."employees";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."employees";
DROP POLICY IF EXISTS "Managers can add new employees" ON "public"."employees";
DROP POLICY IF EXISTS "Managers can delete employees" ON "public"."employees";
DROP POLICY IF EXISTS "Managers can manage employees" ON "public"."employees";
DROP POLICY IF EXISTS "Managers can update employee information" ON "public"."employees";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."employees";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."employees";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."employees";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."employees";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."employees";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."employees";
DROP POLICY IF EXISTS "Users can manage their own employees" ON "public"."employees";
DROP POLICY IF EXISTS "Allow user access to their own halls" ON "public"."halls";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."halls";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."halls";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."halls";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."halls";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."halls";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."halls";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."halls";
DROP POLICY IF EXISTS "Allow user access to their own ingredient categories" ON "public"."ingredient_categories";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."ingredient_categories";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."ingredient_categories";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."ingredient_categories";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."ingredient_categories";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."ingredient_categories";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."ingredient_categories";
DROP POLICY IF EXISTS "Allow user access to their own ingredients" ON "public"."ingredients";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."ingredients";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."ingredients";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."ingredients";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."ingredients";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."ingredients";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."ingredients";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."ingredients";
DROP POLICY IF EXISTS "Allow user access to their own order items" ON "public"."order_items";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."order_items";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."order_items";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."order_items";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."order_items";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."order_items";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."order_items";
DROP POLICY IF EXISTS "Permitir criação pública de itens de pedido" ON "public"."order_items";
DROP POLICY IF EXISTS "Permitir leitura pública de itens de pedido" ON "public"."order_items";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."order_items";
DROP POLICY IF EXISTS "Allow user access to their own orders" ON "public"."orders";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."orders";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."orders";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."orders";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."orders";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."orders";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."orders";
DROP POLICY IF EXISTS "Permitir criação pública de pedidos" ON "public"."orders";
DROP POLICY IF EXISTS "Permitir leitura pública de pedidos" ON "public"."orders";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."orders";
DROP POLICY IF EXISTS "Allow user access to their own recipe categories" ON "public"."categories";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."categories";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."categories";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."categories";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."categories";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."categories";
DROP POLICY IF EXISTS "Permitir leitura pública de categorias" ON "public"."categories";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."categories";
DROP POLICY IF EXISTS "Allow user access to their own recipe ingredients" ON "public"."recipe_ingredients";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."recipe_ingredients";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."recipe_ingredients";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."recipe_ingredients";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."recipe_ingredients";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."recipe_ingredients";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."recipe_ingredients";
DROP POLICY IF EXISTS "Allow user access to their own recipe preparations" ON "public"."recipe_preparations";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."recipe_preparations";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."recipe_preparations";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."recipe_preparations";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."recipe_preparations";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."recipe_preparations";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."recipe_preparations";
DROP POLICY IF EXISTS "Allow user access to their own recipes" ON "public"."recipes";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."recipes";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."recipes";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."recipes";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."recipes";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."recipes";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."recipes";
DROP POLICY IF EXISTS "Permitir leitura pública de receitas" ON "public"."recipes";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."recipes";
DROP POLICY IF EXISTS "Allow user access to their own stations" ON "public"."stations";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."stations";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."stations";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."stations";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."stations";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."stations";
DROP POLICY IF EXISTS "Permitir leitura pública de estações" ON "public"."stations";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."stations";
DROP POLICY IF EXISTS "Allow user access to their own suppliers" ON "public"."suppliers";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."suppliers";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."suppliers";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."suppliers";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."suppliers";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."suppliers";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."suppliers";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."suppliers";
DROP POLICY IF EXISTS "Allow user access to their own tables" ON "public"."tables";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."tables";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."tables";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."tables";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."tables";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."tables";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."tables";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."tables";
DROP POLICY IF EXISTS "Allow user access to their own transactions" ON "public"."transactions";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."transactions";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."transactions";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."transactions";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."transactions";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."transactions";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."transactions";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."transactions";
DROP POLICY IF EXISTS "Allow users to delete their own webhooks" ON "public"."webhooks";
DROP POLICY IF EXISTS "Allow users to insert their own webhooks" ON "public"."webhooks";
DROP POLICY IF EXISTS "Allow users to see their own webhooks" ON "public"."webhooks";
DROP POLICY IF EXISTS "Allow users to update their own webhooks" ON "public"."webhooks";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."webhooks";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."webhooks";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."webhooks";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."webhooks";
DROP POLICY IF EXISTS "Allow users to manage their own company profile" ON "public"."company_profile";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."company_profile";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."company_profile";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."company_profile";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."company_profile";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."company_profile";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."company_profile";
DROP POLICY IF EXISTS "Permitir leitura pública do perfil da empresa" ON "public"."company_profile";
DROP POLICY IF EXISTS "Allow users to manage their own purchase order items" ON "public"."purchase_order_items";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."purchase_order_items";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."purchase_order_items";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."purchase_order_items";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."purchase_order_items";
DROP POLICY IF EXISTS "Allow users to manage their own purchase orders" ON "public"."purchase_orders";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."purchase_orders";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."purchase_orders";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."purchase_orders";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."purchase_orders";
DROP POLICY IF EXISTS "Allow users to manage their own sub-recipe links" ON "public"."recipe_sub_recipes";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."recipe_sub_recipes";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."recipe_sub_recipes";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."recipe_sub_recipes";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."recipe_sub_recipes";
DROP POLICY IF EXISTS "Allow users to read their own subscription" ON "public"."subscriptions";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."subscriptions";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."subscriptions";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."subscriptions";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."subscriptions";
DROP POLICY IF EXISTS "Anyone can create a reservation" ON "public"."reservations";
DROP POLICY IF EXISTS "Authenticated users can manage their own reservations" ON "public"."reservations";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."reservations";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."reservations";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."reservations";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."reservations";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."reservations";
DROP POLICY IF EXISTS "Authenticated users can manage their own settings" ON "public"."reservation_settings";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."reservation_settings";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."reservation_settings";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."reservation_settings";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."reservation_settings";
DROP POLICY IF EXISTS "Permitir leitura pública de configurações de reserva" ON "public"."reservation_settings";
DROP POLICY IF EXISTS "Settings are public to read if enabled" ON "public"."reservation_settings";
DROP POLICY IF EXISTS "Employees can manage their own leave requests" ON "public"."leave_requests";
DROP POLICY IF EXISTS "Managers can view all leave requests" ON "public"."leave_requests";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."leave_requests";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."leave_requests";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."leave_requests";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."leave_requests";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."promotion_recipes";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."promotion_recipes";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."promotion_recipes";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."promotion_recipes";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."promotion_recipes";
DROP POLICY IF EXISTS "Permitir leitura pública de receitas em promoção" ON "public"."promotion_recipes";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."promotion_recipes";
DROP POLICY IF EXISTS "Users can manage their own promotion recipes" ON "public"."promotion_recipes";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."promotions";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."promotions";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."promotions";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."promotions";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."promotions";
DROP POLICY IF EXISTS "Permitir leitura pública de promoções" ON "public"."promotions";
DROP POLICY IF EXISTS "Users can manage their own data" ON "public"."promotions";
DROP POLICY IF EXISTS "Users can manage their own promotions" ON "public"."promotions";
DROP POLICY IF EXISTS "Enable all for users based on user_id" ON "public"."time_clock_entries";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."time_clock_entries";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."time_clock_entries";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."time_clock_entries";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."time_clock_entries";
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON "public"."production_plans";
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON "public"."production_plans";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."production_plans";
DROP POLICY IF EXISTS "Enable update for authenticated users" ON "public"."production_plans";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."production_plans";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."production_plans";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."production_plans";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."production_plans";
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON "public"."production_tasks";
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON "public"."production_tasks";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."production_tasks";
DROP POLICY IF EXISTS "Enable update for authenticated users" ON "public"."production_tasks";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."production_tasks";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."production_tasks";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."production_tasks";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."production_tasks";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."production_tasks";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."assets_depreciation";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."customers";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."customers";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."customers";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."customers";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."customers";
DROP POLICY IF EXISTS "Users can manage their own customers" ON "public"."customers";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."financial_categories";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."ifood_webhook_logs";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."ifood_webhook_logs";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."ifood_webhook_logs";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."ifood_webhook_logs";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."ifood_webhook_logs";
DROP POLICY IF EXISTS "Usuários podem visualizar seus próprios logs de webhook" ON "public"."ifood_webhook_logs";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."inventory_adjustments";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."inventory_logs";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."inventory_logs";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."inventory_logs";
DROP POLICY IF EXISTS "Multi-tenant access policy" ON "public"."requisitions";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."requisitions";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."requisitions";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."requisitions";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."requisitions";
DROP POLICY IF EXISTS "Users can delete requisitions of their own restaurant" ON "public"."requisitions";
DROP POLICY IF EXISTS "Users can insert requisitions for their own restaurant" ON "public"."requisitions";
DROP POLICY IF EXISTS "Users can update requisitions of their own restaurant" ON "public"."requisitions";
DROP POLICY IF EXISTS "Users can view requisitions of their own restaurant" ON "public"."requisitions";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."delivery_drivers";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."delivery_drivers";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."delivery_drivers";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."delivery_drivers";
DROP POLICY IF EXISTS "Users can manage their own delivery drivers" ON "public"."delivery_drivers";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."inventory_lots";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."inventory_lots";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."inventory_lots";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."inventory_lots";
DROP POLICY IF EXISTS "Users can manage their own inventory lots" ON "public"."inventory_lots";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."label_logs";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."label_logs";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."label_logs";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."label_logs";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."payroll_adjustments";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."payroll_adjustments";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."payroll_adjustments";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."payroll_adjustments";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."portioning_event_outputs";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."portioning_event_outputs";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."portioning_event_outputs";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."portioning_event_outputs";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."portioning_events";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."portioning_events";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."portioning_events";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."portioning_events";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."requisition_items";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."requisition_items";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."requisition_items";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."requisition_items";
DROP POLICY IF EXISTS "Users can delete requisition items of their own restaurant" ON "public"."requisition_items";
DROP POLICY IF EXISTS "Users can insert requisition items for their own restaurant" ON "public"."requisition_items";
DROP POLICY IF EXISTS "Users can update requisition items of their own restaurant" ON "public"."requisition_items";
DROP POLICY IF EXISTS "Users can view requisition items of their own restaurant" ON "public"."requisition_items";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."requisition_templates";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."requisition_templates";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."requisition_templates";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."role_permissions";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."role_permissions";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."role_permissions";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."role_permissions";
DROP POLICY IF EXISTS "Users can manage permissions for their own roles." ON "public"."role_permissions";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."roles";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."roles";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."roles";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."roles";
DROP POLICY IF EXISTS "Users can manage their own roles." ON "public"."roles";
DROP POLICY IF EXISTS "Multi-unit Access Delete" ON "public"."station_stocks";
DROP POLICY IF EXISTS "Multi-unit Access Insert" ON "public"."station_stocks";
DROP POLICY IF EXISTS "Multi-unit Access Select" ON "public"."station_stocks";
DROP POLICY IF EXISTS "Multi-unit Access Update" ON "public"."station_stocks";
DROP POLICY IF EXISTS "Users can delete station stocks of their own restaurant" ON "public"."station_stocks";
DROP POLICY IF EXISTS "Users can insert station stocks for their own restaurant" ON "public"."station_stocks";
DROP POLICY IF EXISTS "Users can update station stocks of their own restaurant" ON "public"."station_stocks";
DROP POLICY IF EXISTS "Users can view station stocks of their own restaurant" ON "public"."station_stocks";
DROP POLICY IF EXISTS "Multi-unit Access Delete Items" ON "public"."requisition_template_items";
DROP POLICY IF EXISTS "Multi-unit Access Insert Items" ON "public"."requisition_template_items";
DROP POLICY IF EXISTS "Multi-unit Access Select Items" ON "public"."requisition_template_items";
DROP POLICY IF EXISTS "Multi-unit Access Delete checklist_templates" ON "public"."checklist_templates";
DROP POLICY IF EXISTS "Multi-unit Access Insert checklist_templates" ON "public"."checklist_templates";
DROP POLICY IF EXISTS "Multi-unit Access Select checklist_templates" ON "public"."checklist_templates";
DROP POLICY IF EXISTS "Multi-unit Access Update checklist_templates" ON "public"."checklist_templates";
DROP POLICY IF EXISTS "Multi-unit Access Delete equipment" ON "public"."equipment";
DROP POLICY IF EXISTS "Multi-unit Access Insert equipment" ON "public"."equipment";
DROP POLICY IF EXISTS "Multi-unit Access Select equipment" ON "public"."equipment";
DROP POLICY IF EXISTS "Multi-unit Access Update equipment" ON "public"."equipment";
DROP POLICY IF EXISTS "Multi-unit Access Insert checklist_logs" ON "public"."checklist_logs";
DROP POLICY IF EXISTS "Multi-unit Access Select checklist_logs" ON "public"."checklist_logs";
DROP POLICY IF EXISTS "Multi-unit Access Update checklist_logs" ON "public"."checklist_logs";
DROP POLICY IF EXISTS "Multi-unit Access Insert temperature_logs" ON "public"."temperature_logs";
DROP POLICY IF EXISTS "Multi-unit Access Select temperature_logs" ON "public"."temperature_logs";
DROP POLICY IF EXISTS "Multi-unit Access Update temperature_logs" ON "public"."temperature_logs";
DROP POLICY IF EXISTS "Perfis são visíveis para todos." ON "public"."profiles";
DROP POLICY IF EXISTS "Users can update their own profile." ON "public"."profiles";
DROP POLICY IF EXISTS "Users can view their own profile." ON "public"."profiles";
DROP POLICY IF EXISTS "Usuários podem atualizar seus próprios perfis." ON "public"."profiles";
DROP POLICY IF EXISTS "Usuários podem criar seus próprios perfis." ON "public"."profiles";
DROP POLICY IF EXISTS "Permitir inserção pública para testadores beta" ON "public"."beta_testers";
DROP POLICY IF EXISTS "Permitir leitura de lojas" ON "public"."stores";
DROP POLICY IF EXISTS "Users can delete their own stores" ON "public"."stores";
DROP POLICY IF EXISTS "Users can insert their own stores" ON "public"."stores";
DROP POLICY IF EXISTS "Users can update their own stores" ON "public"."stores";
DROP POLICY IF EXISTS "Users can view their own stores" ON "public"."stores";
DROP POLICY IF EXISTS "Visibilidade da Loja" ON "public"."stores";
DROP POLICY IF EXISTS "Permitir leitura pública" ON "public"."forum_edits";
DROP POLICY IF EXISTS "Posts publicados são visíveis para todos." ON "public"."posts";
DROP POLICY IF EXISTS "Usuários autenticados podem criar posts." ON "public"."posts";
DROP POLICY IF EXISTS "Usuários podem atualizar seus próprios posts." ON "public"."posts";
DROP POLICY IF EXISTS "Usuários podem deletar seus próprios posts." ON "public"."posts";
DROP POLICY IF EXISTS "Stores can see their managers" ON "public"."unit_permissions";
DROP POLICY IF EXISTS "Users can view their own permissions" ON "public"."unit_permissions";
DROP POLICY IF EXISTS "System cache is private" ON "public"."system_cache";
DROP POLICY IF EXISTS "Templates publicados são visíveis para todos." ON "public"."templates";
DROP POLICY IF EXISTS "Usuários autenticados podem criar templates." ON "public"."templates";
DROP POLICY IF EXISTS "Usuários podem atualizar seus próprios templates." ON "public"."templates";
DROP POLICY IF EXISTS "Usuários podem deletar seus próprios templates." ON "public"."templates";
DROP POLICY IF EXISTS "Users can delete their own data" ON "public"."user_tool_data";
DROP POLICY IF EXISTS "Users can insert their own data" ON "public"."user_tool_data";
DROP POLICY IF EXISTS "Users can update their own data" ON "public"."user_tool_data";
DROP POLICY IF EXISTS "Users can view their own data" ON "public"."user_tool_data";
DROP POLICY IF EXISTS "Users can view their own permissions" ON "public"."user_permissions";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."ifood_option_groups";
DROP POLICY IF EXISTS "Permitir leitura publica" ON "public"."ifood_option_groups";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."ifood_options";
DROP POLICY IF EXISTS "Permitir leitura publica" ON "public"."ifood_options";
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON "public"."recipe_ifood_option_groups";
DROP POLICY IF EXISTS "Permitir leitura publica" ON "public"."recipe_ifood_option_groups";
DROP POLICY IF EXISTS "Users can view their own agent configs" ON "public"."whatsapp_agent_configs";
DROP POLICY IF EXISTS "Users can insert their own agent configs" ON "public"."whatsapp_agent_configs";
DROP POLICY IF EXISTS "Users can update their own agent configs" ON "public"."whatsapp_agent_configs";

CREATE POLICY "Enable multi-tenant access" ON "public"."requisitions" USING (has_access_to_store(user_id) OR (target_unit_id IS NOT NULL AND has_access_to_store(target_unit_id))) WITH CHECK (has_access_to_store(user_id) OR (target_unit_id IS NOT NULL AND has_access_to_store(target_unit_id)));
CREATE POLICY "Enable multi-tenant access" ON "public"."requisition_items" USING (has_access_to_store(user_id) OR EXISTS (SELECT 1 FROM requisitions r WHERE r.id = requisition_id AND r.target_unit_id IS NOT NULL AND has_access_to_store(r.target_unit_id))) WITH CHECK (has_access_to_store(user_id) OR EXISTS (SELECT 1 FROM requisitions r WHERE r.id = requisition_id AND r.target_unit_id IS NOT NULL AND has_access_to_store(r.target_unit_id)));
